### ISSUE TITLE
Question: Why strict version requirement on Infomap

### ISSUE THREAD

**Issue by VRehnberg** [ulfaslak/infostop#23]
The Infomap version requirement was made strict in commit [8df4e551](https://github.com/ulfaslak/infostop/commit/8df4e55159d9880960e254a6dd280071f24d40e9). What's the reason for this?

I couldn't find any braking changes mentioned in the [changelog](https://github.com/mapequation/infomap/blob/master/CHANGELOG.md) that would be problematic (the only use of infomap I found was [here](https://github.com/ulfaslak/infostop/blob/8593880fbda6008d3cdb768d30cf2df8cad74b79/infostop/utils.py#L4)).

Incidentally, if I would investigate if this can be relaxed do you have an idea what is susceptible to break (so I know what tests would be sufficient to tell whether it works or not).

**Comment by VRehnberg** [comment]
So after some light testing I don't see any issues with 2.7.1 at least.

**Comment by ulfaslak** [comment]
Some braking changes to Infomap (API changes), happened after we built this, so I set the hard requirement on versioning. This should be updated though. You are welcome to raise another issue asking for an update to the requirement. And as always, since I'm too busy with life right now to actually do it, your contribution in the form of a PR is MUCH appreciated 🙏.
