### ISSUE TITLE
Measure of time

### ISSUE THREAD

**Issue by janpiskur** [ulfaslak/infostop#4]
Hi,

Thanks for the code. Interesting project. :-)

I am currently debugging and need to make sure I understand this code. What is the measure of time for min_staying_time, max_time_between, and the third column of the input data (coords) to the label_trace function? Is it seconds? Does the time component of the input data (coords) start from 0 seconds and just increase incrementally or is it some fancy thing like seconds since January 1, 1970 I should be aware of? 

I am currently working with vehicles and I want to figure out when they have parked for more than 2 hours. The code is working fine for the default value 300 (seconds?), but when I increase the value to 2 hours (or 7200 seconds to be more precise) I get the error below. What is going on here (the data I am working on does have data points with more than 2 hours parking, so I am not sure I understand)?
---------------------------error----------------------------
raise Exception("No edges added because `r2 < np.nanmin(D)`. The minimum and median pairwise distances are %.03f and %.03f, respectively, consider setting `r2` with regard to these." % (np.nanmin(D), np.nanmedian(D)))

Exception: No edges added because `r2 < np.nanmin(D)`. The minimum and median pairwise distances are 72.226 and 13318.111, respectively, consider setting `r2` with regard to these.
---------------------------error----------------------------

Best regards

**Comment by ulfaslak** [comment]
Hi! Sorry for the late answer, I simply missed the notification.

> What is the measure of time for min_staying_time, max_time_between, and the third column of the input data (coords) to the label_trace function?

I recommend setting everything to seconds, but actually it doesn't matter, as long as you are consistent with what time unit you are using. So it also doesn't have to be UNIX time (since 1970 as you suggest), because all that matters for recording time is the time *between* events.

> I am currently working with vehicles and I want to figure out when they have parked for more than 2 hours. The code is working fine for the default value 300 (seconds?), but when I increase the value to 2 hours (or 7200 seconds to be more precise) I get the error below. What is going on here (the data I am working on does have data points with more than 2 hours parking, so I am not sure I understand)?

Cool problem! You have understood the parameters correctly I think, but this error is definitely because of what it says. Can you assert that when `min_staying_time==300` you have stationary events that are longer than 2 hours? I this case there is a problem. Can you maybe provide a minimal example that reproduces the error?
